### ISSUE TITLE
This probably only works on Simons machine 🙂

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/youseedee#2]
I reached here because it is an (undeclared) [flux](https://github.com/simoncozens/flux) dependency, but I can’t get it to work.

I had to first install `requests` (there are no listed dependencies), then it trackbacks:
```
Downloading Unicode Character Database...
[==================================================]Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/khaled/Development/attic/flux/Flux/__main__.py", line 128, in <module>
    FluxEditor(proj).show()
  File "/Users/khaled/Development/attic/flux/Flux/__main__.py", line 39, in __init__
    self.shapingDebugger = QShapingDebugger(self.project)
  File "/Users/khaled/Development/attic/flux/Flux/UI/qshapingdebugger.py", line 25, in __init__
    self.shapeText()
  File "/Users/khaled/Development/attic/flux/Flux/UI/qshapingdebugger.py", line 28, in shapeText
    buf = Buffer(self.project.font.font, unicodes=self.text, direction="RTL")
  File "/Users/khaled/Development/attic/fontfeatures/fontFeatures/jankyPOS/Buffer.py", line 72, in __init__
    self.guess_segment_properties()
  File "/Users/khaled/Development/attic/fontfeatures/fontFeatures/jankyPOS/Buffer.py", line 82, in guess_segment_properties
    thisScript = ucd_data(u.codepoint)["Script"]
  File "/Users/khaled/Development/attic/flux/env/lib/python3.8/site-packages/youseedee/__init__.py", line 176, in ucd_data
    out.update(props["datareader"](file, codepoint))
  File "/Users/khaled/Development/attic/flux/env/lib/python3.8/site-packages/youseedee/__init__.py", line 73, in dictget
    fileentry["data"] = fileentry["reader"](filename)
  File "/Users/khaled/Development/attic/flux/env/lib/python3.8/site-packages/youseedee/__init__.py", line 60, in parse_file_semicolonsep
    with open(os.path.join(ucd_dir(), filename), "r", newline='') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/khaled/.youseedee/USECategory.txt
```

There are many files under `~/.youseedee` (yay for saving files in the home directory), but no `USECategory.txt` indeed,

**Comment by simoncozens** [comment]
Oh oops. I'm going to comment that out for now, until I finish the USE engine implementation. Then I will try to remember how I derived that file. ;-)

**Comment by simoncozens** [comment]
Fixed in bf1e705 but keeping this issue open to remind me to make a better fix.

**Comment by simoncozens** [comment]
Actually I think what I did was a hacked version of Harfbuzz's `dump-use-data`.

**Comment by khaledhosny** [comment]
Works now, thanks!

**Comment by simoncozens** [comment]
And now I've embedded the USE data.
